<?php

use Illuminate\Database\Seeder;
use App\CityCode;

class cityCodeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CityCode::create(['code_iata' =>'ABC','name'=>'Aeropuerto de Albacete','serves'=>'Albacete','state'=>'Castilla-La Mancha','country_id'=>'1']);
        CityCode::create(['code_iata' =>'ABC','name'=>'Base Aérea de Los Llanos','serves'=>'Albacete','state'=>'Castilla-La Mancha','country_id'=>'1']);
        CityCode::create(['code_iata' =>'AEP','name'=>'Aeroparque Jorge Newbery','serves'=>'Buenos Aires','state'=>'Buenos Aires','country_id'=>'2']);
        CityCode::create(['code_iata' =>'AFA','name'=>'Aeropuerto Internacional Suboficial Ayudante Santiago Germano','serves'=>'San Rafael','state'=>'Mendoza','country_id'=>'2']);
        CityCode::create(['code_iata' =>'AMS','name'=>'Aeropuerto de Ámsterdam-Schiphol','serves'=>'Ámsterdam','state'=>'Holanda Septentrional','country_id'=>'3']);
        CityCode::create(['code_iata' =>'AOL','name'=>'Aeropuerto Internacional de Paso de los Libres','serves'=>'Paso de los Libres','state'=>'Córdoba','country_id'=>'2']);
        CityCode::create(['code_iata' =>'ARI','name'=>'Aeropuerto Internacional Chacalluta','serves'=>'Arica','state'=>'Arica y Parinacota','country_id'=>'4']);
        CityCode::create(['code_iata' =>'ARN','name'=>'Aeropuerto de Estocolmo-Arlanda','serves'=>'Estocolmo','state'=>'Provincia de Estocolmo','country_id'=>'5']);
        CityCode::create(['code_iata' =>'ASU','name'=>'Aeropuerto Internacional Silvio Pettirossi','serves'=>'Luque','state'=>'Central','country_id'=>'6']);
        CityCode::create(['code_iata' =>'ATH','name'=>'Aeropuerto Internacional Eleftherios Venizelos','serves'=>'Atenas','state'=>'Ática','country_id'=>'7']);
        CityCode::create(['code_iata' =>'AUA','name'=>'Aeropuerto Internacional Reina Beatrix','serves'=>'Oranjestad','state'=>'Aruba','country_id'=>'3']);
        CityCode::create(['code_iata' =>'BCN','name'=>'Aeropuerto de Barcelona-El Prat','serves'=>'Barcelona','state'=>'Cataluña','country_id'=>'1']);
        CityCode::create(['code_iata' =>'BIN','name'=>'Aeropuerto de Bamiyán','serves'=>'Bamiyán','state'=>'Provincia de Bamiyán','country_id'=>'8']);
        CityCode::create(['code_iata' =>'BOD','name'=>'Aeropuerto de Burdeos-Mérignac','serves'=>'Burdeos','state'=>'Aquitania','country_id'=>'9']);
        CityCode::create(['code_iata' =>'BOG','name'=>'Aeropuerto Internacional El Dorado','serves'=>'Bogotá','state'=>'Bogotá','country_id'=>'10']);
        CityCode::create(['code_iata' =>'BPM','name'=>'Base Aérea de Bagram','serves'=>'Bagram','state'=>'Provincia de Parwan','country_id'=>'8']);
        CityCode::create(['code_iata' =>'BSL','name'=>'Aeropuerto de Basilea-Mulhouse-Friburgo','serves'=>'Basilea, Mulhouse, Friburgo','state'=>'Alsacia','country_id'=>'9']);
        CityCode::create(['code_iata' =>'BST','name'=>'Aeropuerto de Bost','serves'=>'Lashkar Gah','state'=>'Provincia de Helmand','country_id'=>'8']);
        CityCode::create(['code_iata' =>'BUD','name'=>'Aeropuerto de Budapest-Ferenc Liszt','serves'=>'Budapest','state'=>'Budapest','country_id'=>'11']);
        CityCode::create(['code_iata' =>'BYJ','name'=>'Base Aérea de Beja','serves'=>'Beja','state'=>'Alentejo','country_id'=>'12']);
        CityCode::create(['code_iata' =>'CCS','name'=>'Aeropuerto Internacional de Maiquetía Simón Bolívar','serves'=>'Caracas','state'=>'Vargas','country_id'=>'13']);
        CityCode::create(['code_iata' =>'CMN','name'=>'Aeropuerto Internacional Mohammed V','serves'=>'Casablanca','state'=>'Región de Casablanca-Settat','country_id'=>'14']);
        CityCode::create(['code_iata' =>'CCC','name'=>'Aeropuerto Internacional de Jardines del Rey','serves'=>'Cayo Coco','state'=>'Ciego de Ávila','country_id'=>'15']);
        CityCode::create(['code_iata' =>'CNQ','name'=>'Aeropuerto Internacional Doctor Fernándo Piragine Niveyro','serves'=>'Ciudad de Corrientes','state'=>'Corrientes','country_id'=>'2']);
        CityCode::create(['code_iata' =>'CLX','name'=>'Aeropuerto Clorinda','serves'=>'Clorinda','state'=>'Formosa','country_id'=>'2']);
        CityCode::create(['code_iata' =>'CGN','name'=>'Aeropuerto Internacional de Colonia/Bonn Konrad Adenauer','serves'=>'Colonia, Bonn','state'=>'Renania del Norte-Westfalia','country_id'=>'16']);
        CityCode::create(['code_iata' =>'CCP','name'=>'Aeropuerto Carriel Sur','serves'=>'Concepción','state'=>'Biobío','country_id'=>'4']);
        CityCode::create(['code_iata' =>'COC','name'=>'Aeropuerto Comodoro Pierrestegui','serves'=>'Concordia','state'=>'Entre Ríos','country_id'=>'2']);
        CityCode::create(['code_iata' =>'CVU','name'=>'Aeropuerto de Corvo','serves'=>'Isla de Corvo','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'CDG','name'=>'Aeropuerto de París-Charles de Gaulle','serves'=>'París','state'=>'Isla de Francia','country_id'=>'9']);
        CityCode::create(['code_iata' =>'CTC','name'=>'Aeropuerto Coronel Felipe Varela','serves'=>'San Fernando del Valle de Catamarca','state'=>'Catamarca','country_id'=>'2']);
        CityCode::create(['code_iata' =>'DAY','name'=>'Aeropuerto Internacional James M. Cox-Dayton','serves'=>'Dayton','state'=>'Ohio','country_id'=>'17']);
        CityCode::create(['code_iata' =>'DJE','name'=>'Aeropuerto Internacional de Yerba-Zarzis','serves'=>'Yerba','state'=>'Medenine','country_id'=>'18']);
        CityCode::create(['code_iata' =>'DME','name'=>'Aeropuerto Internacional de Moscú-Domodédovo','serves'=>'Moscú','state'=>'Óblast de Moscú','country_id'=>'19']);
        CityCode::create(['code_iata' =>'DOH','name'=>'Aeropuerto Internacional Hamad','serves'=>'Doha','state'=>'Municipio de Doha','country_id'=>'20']);
        CityCode::create(['code_iata' =>'DXB','name'=>'Aeropuerto Internacional de Dubái','serves'=>'Dubái','state'=>'Dubái','country_id'=>'21']);
        CityCode::create(['code_iata' =>'EAP','name'=>'Aeropuerto de Basilea-Mulhouse-Friburgo','serves'=>'Basilea, Mulhouse, Friburgo','state'=>'Alsacia','country_id'=>'9']);
        CityCode::create(['code_iata' =>'EDI','name'=>'Aeropuerto de Edimburgo','serves'=>'Edimburgo','state'=>'Escocia','country_id'=>'22']);
        CityCode::create(['code_iata' =>'EGE','name'=>'Aeropuerto Regional del Condado de Eagle','serves'=>'Eagle-Vail','state'=>'Colorado','country_id'=>'17']);
        CityCode::create(['code_iata' =>'EIN','name'=>'Aeropuerto de Eindhoven','serves'=>'Eindhoven','state'=>'Brabante Septentrional','country_id'=>'3']);
        CityCode::create(['code_iata' =>'EZE','name'=>'Aeropuerto Internacional Ministro Pistarini','serves'=>'Ezeiza','state'=>'Buenos Aires','country_id'=>'2']);
        CityCode::create(['code_iata' =>'FAO','name'=>'Aeropuerto de Faro','serves'=>'Faro','state'=>'Algarve','country_id'=>'12']);
        CityCode::create(['code_iata' =>'FBD','name'=>'Aeropuerto de Fayzabad','serves'=>'Fayzabad','state'=>'Provincia de Badajshan','country_id'=>'8']);
        CityCode::create(['code_iata' =>'FCO','name'=>'Aeropuerto de Roma-Fiumicino','serves'=>'Roma','state'=>'Lacio','country_id'=>'23']);
        CityCode::create(['code_iata' =>'FDO','name'=>'Aeropuerto Internacional de San Fernando','serves'=>'San Fernando','state'=>'Buenos Aires','country_id'=>'2']);
        CityCode::create(['code_iata' =>'FLR','name'=>'Aeropuerto de Florencia','serves'=>'Florencia','state'=>'Toscana','country_id'=>'23']);
        CityCode::create(['code_iata' =>'FLW','name'=>'Aeropuerto de Flores','serves'=>'Isla de Flores','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'FMA','name'=>'Aeropuerto Internacional de Formosa','serves'=>'Ciudad de Formosa','state'=>'Formosa','country_id'=>'2']);
        CityCode::create(['code_iata' =>'FNC','name'=>'Aeropuerto Internacional Cristiano Ronaldo','serves'=>'Funchal','state'=>'Madeira','country_id'=>'12']);
        CityCode::create(['code_iata' =>'FRA','name'=>'Aeropuerto de Fráncfort del Meno','serves'=>'Fráncfort del Meno','state'=>'Hesse','country_id'=>'16']);
        CityCode::create(['code_iata' =>'HAJ','name'=>'Aeropuerto de Hannover','serves'=>'Hannover','state'=>'Baja Sajonia','country_id'=>'16']);
        CityCode::create(['code_iata' =>'HAM','name'=>'Aeropuerto de Hamburgo','serves'=>'Hamburgo','state'=>'Hamburgo','country_id'=>'16']);
        CityCode::create(['code_iata' =>'HEA','name'=>'Aeropuerto de Herat','serves'=>'Herat','state'=>'Provincia de Herat','country_id'=>'8']);
        CityCode::create(['code_iata' =>'HEL','name'=>'Aeropuerto de Helsinki-Vantaa','serves'=>'Helsinki','state'=>'Uusimaa','country_id'=>'24']);
        CityCode::create(['code_iata' =>'HGL','name'=>'Aeropuerto de Heligoland','serves'=>'Heligoland','state'=>'Schleswig-Holstein','country_id'=>'16']);
        CityCode::create(['code_iata' =>'HHN','name'=>'Aeropuerto de Fráncfort-Hahn','serves'=>'Fráncfort','state'=>'Renania del Norte-Westfalia','country_id'=>'16']);
        CityCode::create(['code_iata' =>'HKJ','name'=>'Aeropuerto Internacional de Hong Kong','serves'=>'Hong Kong','state'=>'Región Administrativa Especial de Hong Kong','country_id'=>'25']);
        CityCode::create(['code_iata' =>'HNL','name'=>'Aeropuerto Internacional de Honolulu','serves'=>'Honolulu','state'=>'Hawái','country_id'=>'17']);
        CityCode::create(['code_iata' =>'HOR','name'=>'Aeropuerto de Horta','serves'=>'Isla de Faial','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'IBZ','name'=>'Aeropuerto de Ibiza','serves'=>'Ibiza','state'=>'Islas Baleares','country_id'=>'1']);
        CityCode::create(['code_iata' =>'ICN','name'=>'Aeropuerto Internacional de Incheon','serves'=>'Incheon, Seúl','state'=>'Ciudad Metropolitana de Incheon','country_id'=>'26']);
        CityCode::create(['code_iata' =>'INV','name'=>'Aeropuerto de Inverness','serves'=>'Inverness','state'=>'Escocia','country_id'=>'22']);
        CityCode::create(['code_iata' =>'IPC','name'=>'Aeropuerto Internacional Mataveri','serves'=>'Isla de Pascua','state'=>'Valparaíso','country_id'=>'4']);
        CityCode::create(['code_iata' =>'IRJ','name'=>'Aeropuerto Capitán Vicente Almandos Almonacid','serves'=>'Ciudad de La Rioja','state'=>'La Rioja','country_id'=>'2']);
        CityCode::create(['code_iata' =>'IST','name'=>'Aeropuerto Internacional Atatürk','serves'=>'Estambul','state'=>'Provincia de Estambul','country_id'=>'27']);
        CityCode::create(['code_iata' =>'IVL','name'=>'Aeropuerto de Ivalo','serves'=>'Ivalo','state'=>'Laponia finlandesa','country_id'=>'24']);
        CityCode::create(['code_iata' =>'JAA','name'=>'Aeropuerto de Jalalabad','serves'=>'Jalalabad','state'=>'Provincia de Nangar','country_id'=>'8']);
        CityCode::create(['code_iata' =>'JER','name'=>'Aeropuerto de Jersey','serves'=>'Saint Helier','state'=>'Jersey','country_id'=>'22']);
        CityCode::create(['code_iata' =>'JFK','name'=>'Aeropuerto Internacional John F. Kennedy','serves'=>'Nueva York','state'=>'Nueva York','country_id'=>'17']);
        CityCode::create(['code_iata' =>'JKL','name'=>'Aeropuerto Nacional de Kálimnos','serves'=>'Pothia (en)','state'=>'Egeo Meridional','country_id'=>'7']);
        CityCode::create(['code_iata' =>'JSR','name'=>'Aeropuerto de Jessore','serves'=>'Jessore (en)','state'=>'Khulna','country_id'=>'28']);
        CityCode::create(['code_iata' =>'KBL','name'=>'Aeropuerto Internacional de Kabul','serves'=>'Kabul','state'=>'Provincia de Kabul','country_id'=>'8']);
        CityCode::create(['code_iata' =>'KDH','name'=>'Aeropuerto Internacional de Kandahar','serves'=>'Kandahar','state'=>'Provincia de Kandahar','country_id'=>'8']);
        CityCode::create(['code_iata' =>'KEF','name'=>'Aeropuerto Internacional de Keflavík','serves'=>'Reikiavik','state'=>'Höfuðborgarsvæðið','country_id'=>'29']);
        CityCode::create(['code_iata' =>'KGD','name'=>'Aeropuerto de Kaliningrado-Jrabrovo','serves'=>'Kaliningrado','state'=>'Óblast de Kaliningrado','country_id'=>'19']);
        CityCode::create(['code_iata' =>'LAD','name'=>'Aeropuerto Internacional Quatro de Fevereiro','serves'=>'Luanda','state'=>'Provincia de Luanda','country_id'=>'30']);
        CityCode::create(['code_iata' =>'LAX','name'=>'Aeropuerto Internacional de Los Ángeles','serves'=>'Los Ángeles','state'=>'California','country_id'=>'17']);
        CityCode::create(['code_iata' =>'LEU','name'=>'Aeropuerto de Andorra-La Seu','serves'=>"La Seu d'Urgell, Andorra la Vella",'state'=>'Cataluña','country_id'=>'1']);
        CityCode::create(['code_iata' =>'LGG','name'=>'Aeropuerto de Lieja','serves'=>'Lieja','state'=>'Región Valona','country_id'=>'31']);
        CityCode::create(['code_iata' =>'LGS','name'=>'Aeropuerto Internacional Comodoro Ricardo Salomón','serves'=>'Malargüe','state'=>'Mendoza','country_id'=>'2']);
        CityCode::create(['code_iata' =>'LHR','name'=>'Aeropuerto de Heathrow','serves'=>'Londres','state'=>'Inglaterra','country_id'=>'22']);
        CityCode::create(['code_iata' =>'LIM','name'=>'Aeropuerto Internacional Jorge Chávez','serves'=>'Lima​, Callao, Ica','state'=>'Callao','country_id'=>'32']);
        CityCode::create(['code_iata' =>'LIS','name'=>'Aeropuerto de Portela','serves'=>'Lisboa','state'=>'Lisboa','country_id'=>'12']);
        CityCode::create(['code_iata' =>'LTN','name'=>'Aeropuerto de Londres-Luton','serves'=>'Londres','state'=>'Inglaterra','country_id'=>'22']);
        CityCode::create(['code_iata' =>'LUQ','name'=>'Aeropuerto Brigadier Mayor César Raúl Ojeda','serves'=>'Ciudad de San Luis','state'=>'San Luis','country_id'=>'2']);
        CityCode::create(['code_iata' =>'MAD','name'=>'Aeropuerto Adolfo Suárez Madrid-Barajas','serves'=>'Madrid','state'=>'Comunidad de Madrid','country_id'=>'1']);
        CityCode::create(['code_iata' =>'MCS','name'=>'Aeropuerto de Monte Caseros','serves'=>'Monte Caseros','state'=>'Corrientes','country_id'=>'2']);
        CityCode::create(['code_iata' =>'MDQ','name'=>'Aeropuerto Internacional Astor Piazzolla','serves'=>'Mar del Plata','state'=>'Buenos Aires','country_id'=>'2']);
        CityCode::create(['code_iata' =>'MDX','name'=>'Aeropuerto del Iberá','serves'=>'Mercedes','state'=>'Corrientes','country_id'=>'2']);
        CityCode::create(['code_iata' =>'MDZ','name'=>'Aeropuerto Internacional Gobernador Francisco Gabrielli','serves'=>'Ciudad de Mendoza','state'=>'Mendoza','country_id'=>'2']);
        CityCode::create(['code_iata' =>'MFM','name'=>'Aeropuerto Internacional de Macao','serves'=>'Ciudad de Macao','state'=>'Macao','country_id'=>'1']);
        CityCode::create(['code_iata' =>'MKC','name'=>'Aeropuerto Urbano Charles B. Wheeler','serves'=>'Kansas City','state'=>'Misuri','country_id'=>'17']);
        CityCode::create(['code_iata' =>'MLH','name'=>'Aeropuerto de Basilea-Mulhouse-Friburgo','serves'=>'Basilea, Mulhouse, Friburgo','state'=>'Alsacia','country_id'=>'9']);
        CityCode::create(['code_iata' =>'MPN','name'=>'Base Aérea de Monte Agradable','serves'=>'Isla Soledad','state'=>'Islas Malvinas','country_id'=>'22']);
        CityCode::create(['code_iata' =>'MUC','name'=>'Aeropuerto Internacional de Múnich-Franz Josef Strauss','serves'=>'Munich','state'=>'Baviera','country_id'=>'16']);
        CityCode::create(['code_iata' =>'MZR','name'=>'Aeropuerto de Mazar-e Sarif','serves'=>'Mazar-e Sarif','state'=>'Provincia de Balj','country_id'=>'8']);
        CityCode::create(['code_iata' =>'NAP','name'=>'Aeropuerto de Nápoles-Capodichino','serves'=>'Nápoles','state'=>'Campania','country_id'=>'23']);
        CityCode::create(['code_iata' =>'NLK','name'=>'Aeropuerto de la Isla Norfolk (en)','serves'=>'Kingston','state'=>'Norfolk','country_id'=>'33']);
        CityCode::create(['code_iata' =>'OPO','name'=>'Aeropuerto de Francisco Sá Carneiro','serves'=>'Oporto','state'=>'Región Norte','country_id'=>'12']);
        CityCode::create(['code_iata' =>'ORA','name'=>'Aero Club Orán','serves'=>'San Ramón de la Nueva Orán','state'=>'Salta','country_id'=>'2']);
        CityCode::create(['code_iata' =>'ORK','name'=>'Aeropuerto de Cork','serves'=>'Cork','state'=>'Múnster','country_id'=>'34']);
        CityCode::create(['code_iata' =>'ORY','name'=>'Aeropuerto de París-Orly','serves'=>'París','state'=>'Isla de Francia','country_id'=>'9']);
        CityCode::create(['code_iata' =>'OYA','name'=>'Aeropuerto Dr. Diego Nicolás Díaz Colodrero','serves'=>'Goya','state'=>'Corrientes','country_id'=>'2']);
        CityCode::create(['code_iata' =>'PDL','name'=>'Aeropuerto João Paulo II','serves'=>'Isla de São Miguel','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'PHL','name'=>'Aeropuerto Internacional de Filadelfia','serves'=>'Filadelfia','state'=>'Pensilvania','country_id'=>'17']);
        CityCode::create(['code_iata' =>'PIX','name'=>'Aeropuerto de Pico','serves'=>'Isla Pico','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'PRA','name'=>'Aeropuerto General Justo José de Urquiza','serves'=>'Paraná','state'=>'Entre Ríos','country_id'=>'2']);
        CityCode::create(['code_iata' =>'PRQ','name'=>'Aeropuerto de Presidencia Roque Sáenz Peña','serves'=>'Presidencia Roque Sáenz Peña','state'=>'Chaco','country_id'=>'2']);
        CityCode::create(['code_iata' =>'PSY','name'=>'Aeropuerto de Puerto Argentino/Stanley','serves'=>'Puerto Argentino/Stanley','state'=>'Islas Malvinas','country_id'=>'22']);
        CityCode::create(['code_iata' =>'PUQ','name'=>'Aeropuerto Internacional Presidente Carlos Ibáñez del Campo','serves'=>'Punta Arenas','state'=>'Magallanes y Antártica Chilena','country_id'=>'4']);
        CityCode::create(['code_iata' =>'PXO','name'=>'Aeropuerto de Porto Santo','serves'=>'Isla de Porto Santo','state'=>'Madeira','country_id'=>'12']);
        CityCode::create(['code_iata' =>'QGY','name'=>'Aeropuerto Internacional de Györ-Pér','serves'=>'Györ','state'=>'Győr-Moson-Sopron','country_id'=>'11']);
        CityCode::create(['code_iata' =>'QRC','name'=>'Aeródromo de la Independencia','serves'=>'Rancagua','state'=>"O'Higgins",'country_id'=>'4']);
        CityCode::create(['code_iata' =>'QSA','name'=>'Aeropuerto de Sabadell','serves'=>'Sabadell','state'=>'Cataluña','country_id'=>'1']);
        CityCode::create(['code_iata' =>'RAK','name'=>'Aeropuerto de Marrakech-Menara','serves'=>'Marrakech','state'=>'Marrakech-Safí','country_id'=>'14']);
        CityCode::create(['code_iata' =>'RES','name'=>'Aeropuerto Internacional de Resistencia','serves'=>'Ciudad de Resistencia','state'=>'Chaco','country_id'=>'2']);
        CityCode::create(['code_iata' =>'REU','name'=>'Aeropuerto de Reus','serves'=>'Reus, Tarragona','state'=>'Cataluña','country_id'=>'1']);
        CityCode::create(['code_iata' =>'RGA','name'=>'Aeropuerto Internacional Gob. Ramón Trejo Noel','serves'=>'Río Grande','state'=>'Tierra del Fuego','country_id'=>'2']);
        CityCode::create(['code_iata' =>'RHD','name'=>'Aeropuerto Internacional Termas de Río Hondo','serves'=>'Termas de Río Hondo','state'=>'Santiago del Estero','country_id'=>'2']);
        CityCode::create(['code_iata' =>'RLO','name'=>'Aeropuerto Internacional Valle del Conlara','serves'=>'Merlo','state'=>'San Luis','country_id'=>'2']);
        CityCode::create(['code_iata' =>'RRG','name'=>'Aeropuerto Sir Gaëtan Duval','serves'=>'Rodrigues','state'=>'Rodrigues','country_id'=>'35']);
        CityCode::create(['code_iata' =>'RSA','name'=>'Aeropuerto de Santa Rosa','serves'=>'Ciudad de Santa Rosa','state'=>'La Pampa','country_id'=>'2']);
        CityCode::create(['code_iata' =>'SBZ','name'=>'Aeropuerto Internacional de Sibiu','serves'=>'Sibiu','state'=>'Distrito de Sibiu','country_id'=>'36']);
        CityCode::create(['code_iata' =>'SCL','name'=>'Aeropuerto Internacional Comodoro Arturo Merino Benítez','serves'=>'Santiago de Chile','state'=>'Metropolitana de Santiago','country_id'=>'4']);
        CityCode::create(['code_iata' =>'SDE','name'=>'Aeropuerto Vicecomodoro Ángel de la Paz Aragonés','serves'=>'Ciudad de Santiago del Estero','state'=>'Santiago del Estero','country_id'=>'2']);
        CityCode::create(['code_iata' =>'SIN','name'=>'Aeropuerto Internacional de Singapur-Changi','serves'=>'Singapur','state'=>'Consejo del Sudeste','country_id'=>'37']);
        CityCode::create(['code_iata' =>'SJZ','name'=>'Aeropuerto de São Jorge','serves'=>'Isla de São Jorge','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'SKG','name'=>'Aeropuerto Internacional Macedonia','serves'=>'Tesalónica','state'=>'Macedonia Central','country_id'=>'7']);
        CityCode::create(['code_iata' =>'SLA','name'=>'Aeropuerto Internacional de Salta Martín Miguel de Güemes','serves'=>'Ciudad de Salta','state'=>'Salta','country_id'=>'2']);
        CityCode::create(['code_iata' =>'SMA','name'=>'Aeropuerto de Santa Maria','serves'=>'Isla de Santa Maria','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'SNU','name'=>'Aeropuerto Internacional Abel Santamaría','serves'=>'Santa Clara','state'=>'Villa Clara','country_id'=>'15']);
        CityCode::create(['code_iata' =>'SXB','name'=>'Aeropuerto de Estrasburgo','serves'=>'Estrasburgo','state'=>'Alsacia','country_id'=>'9']);
        CityCode::create(['code_iata' =>'SYD','name'=>'Aeropuerto Internacional Kingsford Smith','serves'=>'Sídney','state'=>'Nueva Gales del Sur','country_id'=>'33']);
        CityCode::create(['code_iata' =>'TER','name'=>'Aeropuerto de Lajes','serves'=>'Isla Terceira','state'=>'Azores','country_id'=>'12']);
        CityCode::create(['code_iata' =>'TFN','name'=>'Aeropuerto de Tenerife Norte','serves'=>'Tenerife','state'=>'Canarias','country_id'=>'1']);
        CityCode::create(['code_iata' =>'TFS','name'=>'Aeropuerto de Tenerife Sur','serves'=>'Tenerife','state'=>'Canarias','country_id'=>'1']);
        CityCode::create(['code_iata' =>'THF','name'=>'Aeropuerto de Berlín-Tempelhof','serves'=>'Berlín','state'=>'Berlín','country_id'=>'16']);
        CityCode::create(['code_iata' =>'TLV','name'=>'Aeropuerto Internacional Ben Gurión','serves'=>'Tel Aviv','state'=>'Distrito Central','country_id'=>'38']);
        CityCode::create(['code_iata' =>'TPE','name'=>'Aeropuerto Internacional de Taiwán Taoyuan','serves'=>'Taipéi','state'=>'Taoyuan','country_id'=>'39']);
        CityCode::create(['code_iata' =>'TRS','name'=>'Aeropuerto de Trieste - Friuli Venezia Giulia','serves'=>'Trieste','state'=>'Friuli-Venecia Julia','country_id'=>'23']);
        CityCode::create(['code_iata' =>'TSE','name'=>'Aeropuerto Internacional de Astaná','serves'=>'Astaná','state'=>'Provincia de Akmola','country_id'=>'40']);
        CityCode::create(['code_iata' =>'TTG','name'=>'Aeropuerto General Enrique Mosconi/Tartagal','serves'=>'Tartagal','state'=>'Salta','country_id'=>'2']);
        CityCode::create(['code_iata' =>'TUR','name'=>'Aeropuerto de Turku','serves'=>'Turku','state'=>'Finlandia Propia','country_id'=>'24']);
        CityCode::create(['code_iata' =>'UIO','name'=>'Aeropuerto Internacional Mariscal Sucre','serves'=>'Tababela','state'=>'Pichincha','country_id'=>'41']);
        CityCode::create(['code_iata' =>'USH','name'=>'Aeropuerto Internacional Malvinas Argentinas','serves'=>'Ushuaia','state'=>'Tierra del Fuego','country_id'=>'2']);
        CityCode::create(['code_iata' =>'UZU','name'=>'Aeropuerto de Curuzú Cuatiá','serves'=>'Curuzú Cuatiá','state'=>'Corrientes','country_id'=>'2']);
        CityCode::create(['code_iata' =>'VIE','name'=>'Aeropuerto de Viena-Schwechat','serves'=>'Viena','state'=>'Viena','country_id'=>'42']);
        CityCode::create(['code_iata' =>'VLC','name'=>'Aeropuerto de Valencia','serves'=>'Manises','state'=>'Comunidad Valenciana','country_id'=>'1']);
        CityCode::create(['code_iata' =>'VME','name'=>'Aeropuerto de Villa Reynolds','serves'=>'Villa Mercedes','state'=>'San Luis','country_id'=>'2']);
        CityCode::create(['code_iata' =>'WLG','name'=>'Aeropuerto Internacional de Wellington','serves'=>'Wellington','state'=>'Wellington','country_id'=>'43']);
        CityCode::create(['code_iata' =>'XRY','name'=>'Aeropuerto de Jerez','serves'=>'Jerez','state'=>'Andalucía','country_id'=>'1']);
        CityCode::create(['code_iata' =>'YFB','name'=>'Aeropuerto de Iqaluit','serves'=>'Iqaluit','state'=>'Nunavut','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YHZ','name'=>'Aeropuerto Internacional de Halifax-Stanfield','serves'=>'Halifax','state'=>'Nueva Escocia','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YOW','name'=>'Aeropuerto Internacional de Ottawa','serves'=>'Ottawa','state'=>'Ontario','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YRB','name'=>'Aeropuerto de Resolute Bay','serves'=>'Resolute','state'=>'Nunavut','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YUL','name'=>'Aeropuerto Internacional Pierre Elliott Trudeau','serves'=>'Montreal','state'=>'Quebec','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YVM','name'=>'Aeropuerto de Qikiqtarjuaq','serves'=>'Qikiqtarjuaq (en)','state'=>'Nunavut','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YVR','name'=>'Aeropuerto Internacional de Vancouver','serves'=>'Vancouver','state'=>'Columbia Británica','country_id'=>'44']);
        CityCode::create(['code_iata' =>'YYZ','name'=>'Aeropuerto Internacional Toronto Pearson','serves'=>'Toronto','state'=>'Ontario','country_id'=>'44']);
        CityCode::create(['code_iata' =>'ZAG','name'=>'Aeropuerto de Zagreb-Pleso','serves'=>'Zagreb','state'=>'Condado de Zagreb','country_id'=>'45']);
        CityCode::create(['code_iata' =>'ZAZ','name'=>'Aeropuerto de Zaragoza','serves'=>'Zaragoza','state'=>'Aragón','country_id'=>'1']);
        CityCode::create(['code_iata' =>'CUU','name'=>'A. I. Gral. Roberto Fierro Villalobos o','serves'=>'OMA','state'=>'Chihuahua','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CUU','name'=>'A. I. de Chihuahua','serves'=>'OMA','state'=>'Chihuahua','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CJS','name'=>'A. I. Abraham González o','serves'=>'OMA','state'=>'Chihuahua','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ACN','name'=>'A. I. de Ciudad Acuña','serves'=>'Sociedad* ACITA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LOV','name'=>'A. I. Venustiano Carranza','serves'=>'Sociedad* ACITA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PDS','name'=>'A. I. de Piedras Negras','serves'=>'Sociedad* ACITA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SLW','name'=>'A. I. Plan de Guadalupe o','serves'=>'Sociedad* ACITA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SLW','name'=>'A. I. de Saltillo','serves'=>'Sociedad* ACITA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TRC','name'=>'A. I. Francisco Sarabia o','serves'=>'OMA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TRC','name'=>'A. I. de Torreón','serves'=>'OMA','state'=>'Coahuila','country_id'=>'46']);
        CityCode::create(['code_iata' =>'DGO','name'=>'A. I. Guadalupe Victoria o','serves'=>'OMA','state'=>'Durango','country_id'=>'46']);
        CityCode::create(['code_iata' =>'DGO','name'=>'A. I. de Durango','serves'=>'OMA','state'=>'Durango','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MTY','name'=>'A. I. Gral. Mariano Escobedo o','serves'=>'OMA','state'=>'Nuevo León','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MTY','name'=>'A. I. de Monterrey','serves'=>'OMA','state'=>'Nuevo León','country_id'=>'46']);
        CityCode::create(['code_iata' =>'NTR','name'=>'A. I. del Norte','serves'=>'Privado (secundario)','state'=>'Nuevo León','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SLP','name'=>'A. I. Ponciano Arriaga o','serves'=>'OMA','state'=>'San Luis Potosí','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SLP','name'=>'A. I. de San Luis Potosí','serves'=>'OMA','state'=>'San Luis Potosí','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CVM','name'=>'A. I. Gral. Pedro José Méndez o','serves'=>'ASA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CVM','name'=>'A. I. de Ciudad Victoria','serves'=>'ASA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MAM','name'=>'A. I. Gral. Servando Canales o','serves'=>'ASA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MAM','name'=>'A. I. de Matamoros','serves'=>'ASA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'NLD','name'=>'A. I. Quetzalcóatl o','serves'=>'ASA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'NLD','name'=>'A. I. de Nuevo Laredo','serves'=>'ASA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'REX','name'=>'A. I. Gral. Lucio Blanco o','serves'=>'OMA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'REX','name'=>'A. I. de Reynosa','serves'=>'OMA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TAM','name'=>'A. I. Gral. Fco. Javier Mina o','serves'=>'OMA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TAM','name'=>'A. I. de Tampico','serves'=>'OMA','state'=>'Tamaulipas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ZCL','name'=>'A. I. Gral. Leobardo C. Ruiz o','serves'=>'OMA','state'=>'Zacatecas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ZCL','name'=>'A. I. de Zacatecas','serves'=>'OMA','state'=>'Zacatecas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'AGU','name'=>'A. I. Lic. Jesús Terán Peredo o','serves'=>'GAP','state'=>'Aguascalientes','country_id'=>'46']);
        CityCode::create(['code_iata' =>'AGU','name'=>'A. I. de Aguascalientes','serves'=>'','state'=>'Aguascalientes','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MEX','name'=>'A. I. Benito Juárez','serves'=>'GACM','state'=>'Ciudad de México','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MEX','name'=>'A. I. de la Ciudad de México','serves'=>'GACM','state'=>'Ciudad de México','country_id'=>'46']);
        CityCode::create(['code_iata' =>'BJX','name'=>'A. I. del Bajío o','serves'=>'GAP','state'=>'Guanajuato','country_id'=>'46']);
        CityCode::create(['code_iata' =>'BJX','name'=>'A. I. de Guanajuato','serves'=>'GAP','state'=>'Guanajuato','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TLC','name'=>'A. I. Lic. Adolfo López Mateos o','serves'=>'Sociedad*','state'=>'México','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TLC','name'=>'A. I. de Toluca','serves'=>'Sociedad*','state'=>'México','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CVJ','name'=>'A. I. Gral. Mariano Matamoros o','serves'=>'Sociedad*','state'=>'Morelos','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CVJ','name'=>'A. I. de Cuernavaca','serves'=>'Sociedad*','state'=>'Morelos','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PBC','name'=>'A. I. Hermanos Serdán','serves'=>'ASA','state'=>'Puebla','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PBC','name'=>'A. I. de Puebla','serves'=>'ASA','state'=>'Puebla','country_id'=>'46']);
        CityCode::create(['code_iata' =>'QRO','name'=>'A. I. de Querétaro','serves'=>'Sociedad* AIQ','state'=>'Querétaro','country_id'=>'46']);
        CityCode::create(['code_iata' =>'QRO','name'=>'Región Pacífico','serves'=>'Sociedad* AIQ','state'=>'Querétaro','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CSL','name'=>'A. I. de Cabo San Lucas','serves'=>'Privado','state'=>'Baja California Sur','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LAP','name'=>'A. I. Manuel Márquez de León o','serves'=>'GAP','state'=>'Baja California Sur','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LAP','name'=>'A. I. de La Paz','serves'=>'GAP','state'=>'Baja California Sur','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LTO','name'=>'A. I. de Loreto','serves'=>'ASA','state'=>'Baja California Sur','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SJD','name'=>'A. I. de Los Cabos o','serves'=>'GAP','state'=>'Baja California Sur','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SJD','name'=>'A. I. de San José del Cabo','serves'=>'GAP','state'=>'Baja California Sur','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ESE','name'=>'Base aérea No. 3 o','serves'=>'','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ESE','name'=>'A. I. de Ensenada','serves'=>'','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MXL','name'=>'A. I. Gral. Rodolfo Sánchez Taboada o','serves'=>'GAP','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MXL','name'=>'A. I. de Mexicali','serves'=>'GAP','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SFH','name'=>'A. I. de San Felipe','serves'=>'','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TIJ','name'=>'A. I. Gral. Abelardo L. Rodríguez o','serves'=>'GAP','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TIJ','name'=>'A. I. de Tijuana','serves'=>'GAP','state'=>'Baja California','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ZLO','name'=>'A. I. Playa de Oro o','serves'=>'GAP','state'=>'Colima','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ZLO','name'=>'A. I. de Manzanillo','serves'=>'GAP','state'=>'Colima','country_id'=>'46']);
        CityCode::create(['code_iata' =>'GDL','name'=>'A. I. Miguel Hidalgo y Costilla o','serves'=>'GAP','state'=>'Jalisco','country_id'=>'46']);
        CityCode::create(['code_iata' =>'GDL','name'=>'A. I. de Guadalajara','serves'=>'GAP','state'=>'Jalisco','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PVR','name'=>'A. I. Lic. Gustavo Díaz Ordaz o','serves'=>'GAP','state'=>'Jalisco','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PVR','name'=>'A. I. de Puerto Vallarta','serves'=>'GAP','state'=>'Jalisco','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MLM','name'=>'A. I. Gral. Francisco J. Mujica o','serves'=>'GAP','state'=>'Michoacán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MLM','name'=>'A. I. de Morelia','serves'=>'GAP','state'=>'Michoacán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'UPN','name'=>'A. I. Gra. y Lic. Ignacio López Rayón o','serves'=>'ASA','state'=>'Michoacán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'UPN','name'=>'A. I. de Uruapan','serves'=>'ASA','state'=>'Michoacán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TPQ','name'=>'A. I. Amado Nervo o','serves'=>'ASA','state'=>'Nayarit','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TPQ','name'=>'A. I. de Tepic','serves'=>'ASA','state'=>'Nayarit','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CUL','name'=>'A. I. Federal de Culiacán o','serves'=>'OMA','state'=>'Sinaloa','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CUL','name'=>'A. I. de Bachihualato','serves'=>'OMA','state'=>'Sinaloa','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LMM','name'=>'A. I. Federal del Valle del Fuerte o','serves'=>'GAP','state'=>'Sinaloa','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LMM','name'=>'A. I. de Los Mochis','serves'=>'','state'=>'Sinaloa','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MZT','name'=>'A. I. Gral. Rafael Buelna o','serves'=>'OMA','state'=>'Sinaloa','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MZT','name'=>'A. I. de Mazatlán','serves'=>'','state'=>'Sinaloa','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CEN','name'=>'A. I. de Ciudad Obregón','serves'=>'ASA','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'GYM','name'=>'A. I. Gral. José María Yáñez o','serves'=>'ASA','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'GYM','name'=>'A. I. de Guaymas','serves'=>'','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'HMO','name'=>'A. I. Gral. Ignacio Pesqueira García o','serves'=>'GAP','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'HMO','name'=>'A. I. de Hermosillo','serves'=>'','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'NOG','name'=>'A. I. de Nogales','serves'=>'ASA','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PPE','name'=>'A. I. de Mar de Cortés','serves'=>'Privado','state'=>'Sonora','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CPE','name'=>'A. I. Ing. Alberto Acuña Ongay o','serves'=>'ASA','state'=>'Campeche','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CPE','name'=>'A. I. de Campeche','serves'=>'','state'=>'Campeche','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CME','name'=>'A. I. de Ciudad del Carmen','serves'=>'ASA','state'=>'Campeche','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PQM','name'=>'A. I. de Palenque','serves'=>'Sociedad* GAC','state'=>'Chiapas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TAP','name'=>'A. I. de Tapachula','serves'=>'ASUR','state'=>'Chiapas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TGZ','name'=>'A. I. Ángel Albino Corzo o','serves'=>'Sociedad* GAC','state'=>'Chiapas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TGZ','name'=>'A. I. de Tuxtla Gutiérrez','serves'=>'','state'=>'Chiapas','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ACA','name'=>'A. I. Gral. Juan N. Álvarez o','serves'=>'OMA','state'=>'Guerrero','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ACA','name'=>'A. I. de Acapulco','serves'=>'','state'=>'Guerrero','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ZIH','name'=>'A. I. de Ixtapa-Zihuatanejo','serves'=>'OMA','state'=>'Guerrero','country_id'=>'46']);
        CityCode::create(['code_iata' =>'HUX','name'=>'A. I. de Bahías de Huatulco','serves'=>'ASUR','state'=>'Oaxaca','country_id'=>'46']);
        CityCode::create(['code_iata' =>'OAX','name'=>'A. I. Xoxocotlán o','serves'=>'ASUR','state'=>'Oaxaca','country_id'=>'46']);
        CityCode::create(['code_iata' =>'OAX','name'=>'A. I. de Oaxaca','serves'=>'','state'=>'Oaxaca','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PXM','name'=>'A. I. de Puerto Escondido','serves'=>'ASA','state'=>'Oaxaca','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CUN','name'=>'A. I. de Cancún','serves'=>'ASUR','state'=>'Quintana Roo','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CTM','name'=>'A. I. de Chetumal','serves'=>'ASA','state'=>'Quintana Roo','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CZM','name'=>'A. I. de Cozumel','serves'=>'ASUR','state'=>'Quintana Roo','country_id'=>'46']);
        CityCode::create(['code_iata' =>'VSA','name'=>'A. I. Carlos Rovirosa Pérez o','serves'=>'ASUR','state'=>'Tabasco','country_id'=>'46']);
        CityCode::create(['code_iata' =>'VSA','name'=>'A. I. de Villahermosa','serves'=>'ASUR','state'=>'Tabasco','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MTT','name'=>'A. I. de Minatitlán','serves'=>'ASUR','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'VER','name'=>'A. I. Gral. Heriberto Jara o','serves'=>'ASUR','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'VER','name'=>'A. I. de Veracruz','serves'=>'ASUR','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CZA','name'=>'A. I. de Kaua o','serves'=>'','state'=>'Yucatán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CZA','name'=>'A. I. de Chichén Itzá','serves'=>'','state'=>'Yucatán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MID','name'=>'A. I. Manuel Crescencio Rejón o','serves'=>'ASUR','state'=>'Yucatán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'MID','name'=>'A. I. de Mérida','serves'=>'','state'=>'Yucatán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CLQ','name'=>'A. N. Lic. Miguel de la Madrid','serves'=>'ASA','state'=>'Colima','country_id'=>'46']);
        CityCode::create(['code_iata' =>'LZC','name'=>'A. N. de Lázaro Cárdenas','serves'=>'Gob. Michoacán','state'=>'Michoacán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PAZ','name'=>'A. N. El Tajín','serves'=>'ASA','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'JAL','name'=>'A. N. El Lencero','serves'=>'Gob. Veracruz','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'JAL','name'=>'Aviación general','serves'=>'Gob. Veracruz','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'CYW','name'=>'A. N. Cap. Rogelio Castillo','serves'=>'Patronato del Aeropuerto de Celaya (privado)','state'=>'Guanajuato','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PCA','name'=>'A. N. Ing. Juan Guillermo Villasana','serves'=>'Ayuntamiento de Pachuca','state'=>'Hidalgo','country_id'=>'46']);
        CityCode::create(['code_iata' =>'JJC','name'=>'A. N. Jorge Jiménez Cantú','serves'=>'N/D','state'=>'México','country_id'=>'46']);
        CityCode::create(['code_iata' =>'ZMM','name'=>'A. N. de Zamora','serves'=>'Gob. Michoacán','state'=>'Michoacán','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TCN','name'=>'A. N. de Tehuacán','serves'=>'ASA','state'=>'Puebla','country_id'=>'46']);
        CityCode::create(['code_iata' =>'PCM','name'=>'A. N. de Playa del Carmen','serves'=>'N/D','state'=>'Quintana Roo','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TSL','name'=>'A. N. de Tamuín','serves'=>'ASA','state'=>'San Luis Potosí','country_id'=>'46']);
        CityCode::create(['code_iata' =>'TSL','name'=>'A. N. Juan Antonio Perdomo Díaz','serves'=>'Ayuntamiento de Córdoba','state'=>'Veracruz','country_id'=>'46']);
        CityCode::create(['code_iata' =>'SZT','name'=>'A. N. de San Cristóbal de las Casas','serves'=>'Cerrado en 2010','state'=>'Chiapas','country_id'=>'46']);


        /* fin de aeropuertos méxico*/



    }
}
